import type { NextPage } from 'next';
import Head from 'next/head';

import Join from 'src/components/page/join';

const JoinPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Join />
    </div>
  );
};

export default JoinPage;
