import type { NextPage } from 'next'
import Head from 'next/head'

import Nav from '../src/components/layout/nav';
import Home from '../src/components/page/home';
import Footer from '../src/components/layout/footer';

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <Home />

      <Footer />
    </>
  )
}

export default HomePage;
