import type { NextPage } from 'next';
import Head from 'next/head';

import Start from 'src/components/page/start';
import Layout from 'src/components/layout';

const StartPage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Start />
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
        <h2>TEXT </h2>
      </Layout>
    </>
  );
};

export default StartPage;
