import type { NextPage } from 'next';
import Head from 'next/head';

import Start from '../src/components/page/start';

const StartPage: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Start />
    </div>
  );
};

export default StartPage;
